package net.fayzetwin.siegeconnect

import android.content.Intent
import android.net.VpnService
import android.os.ParcelFileDescriptor
import android.util.Log
import core.Core
import java.io.File

class SiegeVpnService : VpnService() {
    private var vpnInterface: ParcelFileDescriptor? = null
    
    companion object {
        const val ACTION_START = "net.fayzetwin.siegeconnect.START"
        const val ACTION_STOP = "net.fayzetwin.siegeconnect.STOP"
        const val EXTRA_CONFIG_PATH = "config_path"
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        when (intent?.action) {
            ACTION_START -> {
                val configPath = intent.getStringExtra(EXTRA_CONFIG_PATH)
                if (configPath != null) {
                    startVpn(configPath)
                }
            }
            ACTION_STOP -> stopVpn()
        }
        return START_STICKY
    }

    private fun startVpn(configPath: String) {
        if (vpnInterface != null) {
            Log.w("SiegeVpn", "VPN is already running")
            return
        }

        try {
            val builder = Builder()
            builder.setSession("SiegeConnect")
            builder.addAddress("172.19.0.1", 30) // Typical clash tun setup
            builder.addRoute("0.0.0.0", 0)
            builder.addRoute("::", 0)
            builder.addDnsServer("1.1.1.1") // Temporary

            // TODO: App-based split tunneling (addAllowedApplication/addDisallowedApplication)

            vpnInterface = builder.establish()

            // The core.aar was generated by gomobile
            // We start Mihomo passing the directory and config
            val homeDir = File(configPath).parent ?: filesDir.absolutePath
            val configName = File(configPath).name

            // Note: Normally we'd pass the `vpnInterface!!.fd` to the core if it expects it
            // For now, we rely on Mihomo's auto-tun if it supports Android VpnBuilder natively,
            // or we use a custom Go wrapper method.
            Core.startVpn(homeDir, configName)
            
            Log.i("SiegeVpn", "VPN Started successfully")

        } catch (e: Exception) {
            Log.e("SiegeVpn", "Error starting VPN", e)
            stopVpn()
        }
    }

    private fun stopVpn() {
        try {
            Core.stopVpn()
            vpnInterface?.close()
            vpnInterface = null
        } catch (e: Exception) {
            Log.e("SiegeVpn", "Error stopping VPN", e)
        }
        stopSelf()
    }

    override fun onDestroy() {
        stopVpn()
        super.onDestroy()
    }
}
